In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(['EIN', 'NAME'],axis=1)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df['APPLICATION_TYPE'].value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_count[app_count<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df['CLASSIFICATION'].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count[class_count>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
cat_num =  pd.get_dummies(application_df)

In [10]:
# Split our preprocessed data into our features and target arrays
y = cat_num["IS_SUCCESSFUL"]
X = cat_num.drop(columns="IS_SUCCESSFUL")

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
## Compile, Train and Evaluate the Model

In [39]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_feat = len(X_train_scaled[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="relu", input_dim=input_feat))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation="tanh"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=20, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_29 (Dense)            (None, 50)                2200

 dense_30 (Dense)            (None, 50)                2550

 dense_31 (Dense)            (None, 30)                1530

 dense_32 (Dense)            (None, 20)                620

 dense_33 (Dense)            (None, 1)                 21

=================================================================
Total params: 6,921
Trainable params: 6,921
Non-trainable params: 0
_________________________________________________________________

In [40]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [44]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7403
Epoch 2/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7400
Epoch 3/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7401
Epoch 4/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7395
Epoch 5/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7396
Epoch 6/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7395
Epoch 7/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7407
Epoch 8/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7405
Epoch 9/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7391
Epoch 10/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7399
Epoch 11/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7393
Epoch 12/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7396
Epoch 13/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7401
Epoch 14/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7393
Epoch 15/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 16/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7402
Epoch 17/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7408
Epoch 18/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7401
Epoch 19/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7400
Epoch 20/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7395
Epoch 21/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7399
Epoch 22/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7401
Epoch 23/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 24/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7404
Epoch 25/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7398
Epoch 26/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7405
Epoch 27/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7405
Epoch 28/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7407
Epoch 29/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7403
Epoch 30/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7402
Epoch 31/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7406
Epoch 32/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7401
Epoch 33/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7401
Epoch 34/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 35/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7403
Epoch 36/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7399
Epoch 37/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7404
Epoch 38/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7406
Epoch 39/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 40/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 41/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7412
Epoch 42/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7399
Epoch 43/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7401
Epoch 44/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7404
Epoch 45/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7410
Epoch 46/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7408
Epoch 47/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5335 - accuracy: 0.7404
Epoch 48/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7402
Epoch 49/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7411
Epoch 50/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7402
Epoch 51/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 52/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7404
Epoch 53/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7404
Epoch 54/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5330 - accuracy: 0.7404
Epoch 55/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7409
Epoch 56/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 57/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7412
Epoch 58/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7399
Epoch 59/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 60/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 61/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7409
Epoch 62/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7408
Epoch 63/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7404
Epoch 64/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7409
Epoch 65/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7408
Epoch 66/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 67/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7399
Epoch 68/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7400
Epoch 69/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5333 - accuracy: 0.7398
Epoch 70/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7409
Epoch 71/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 72/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 73/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7396
Epoch 74/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 75/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7404
Epoch 76/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5325 - accuracy: 0.7401
Epoch 77/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 78/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7408
Epoch 79/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7399
Epoch 80/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7400
Epoch 81/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 82/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7408
Epoch 83/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7400
Epoch 84/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7411
Epoch 85/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7403
Epoch 86/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7409
Epoch 87/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 88/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 89/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7402
Epoch 90/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 91/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7402
Epoch 92/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7403
Epoch 93/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7404
Epoch 94/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7403
Epoch 95/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7399
Epoch 96/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 97/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7394
Epoch 98/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7402
Epoch 99/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7402
Epoch 100/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7398
Epoch 101/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7399
Epoch 102/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 103/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7402
Epoch 104/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 105/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 106/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7398
Epoch 107/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7408
Epoch 108/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7411
Epoch 109/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7404
Epoch 110/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 111/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7409
Epoch 112/150
804/804 [==============================] - 5s 6ms/step - loss: 0.5333 - accuracy: 0.7404
Epoch 113/150
804/804 [==============================] - 5s 6ms/step - loss: 0.5331 - accuracy: 0.7401
Epoch 114/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5327 - accuracy: 0.7412
Epoch 115/150
804/804 [==============================] - 4s 5ms/step - loss: 0.5329 - accuracy: 0.7411
Epoch 116/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7410
Epoch 117/150
804/804 [==============================] - 3s 3ms/step - loss: 0.5330 - accuracy: 0.7403
Epoch 118/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5337 - accuracy: 0.7404
Epoch 119/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7396
Epoch 120/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7400
Epoch 121/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 122/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7406
Epoch 123/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 124/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7410
Epoch 125/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 126/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7406
Epoch 127/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7402
Epoch 128/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7408
Epoch 129/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5327 - accuracy: 0.7403
Epoch 130/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7407
Epoch 131/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7402
Epoch 132/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 133/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 134/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7395
Epoch 135/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7398
Epoch 136/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7411
Epoch 137/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7408
Epoch 138/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7400
Epoch 139/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 140/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7405
Epoch 141/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7407
Epoch 142/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7400
Epoch 143/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7397
Epoch 144/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7409
Epoch 145/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7398
Epoch 146/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7405
Epoch 147/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7406
Epoch 148/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7404
Epoch 149/150
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7401
Epoch 150/150
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7406

In [45]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5597 - accuracy: 0.7312 - 343ms/epoch - 1ms/step
Loss: 0.5597213506698608, Accuracy: 0.731195330619812

In [52]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

from google.colab import files
files.download('AlphabetSoupCharity_Optimization.h5')